/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 rock3.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

import rock from '~/data/aggro/rock3.gltf';

export function RockModel(props) {
  const { nodes, materials } = useGLTF(rock);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock.geometry} material={nodes.Rock.material} />
    </group>
  );
}

useGLTF.preload(rock);
