name: Deploy beta to Fly.io

on:
  workflow_dispatch:
  push:
    branches:
      - beta

env:
  NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }} # You can find this in your Neon project settings
  FLY_API_TOKEN: ${{ secrets.NEW_FLY_API_TOKEN }} # You can generate a Fly API token in your account settings
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for commenting on pull requests for private repos

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: pr-beta

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create or deploy app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_STAGING }}
          VITE_DEPLOY_ENV: beta
          DATABASE_URL: ${{ steps.create-neon-branch.outputs.db_url_with_pooler }}
        run: |
          flyctl deploy --config ./fly-beta.toml --remote-only \
            --env VITE_DEPLOY_ENV=beta
